### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by slawekjaranowski** [codehaus-plexus/plexus-resources#18]
What license should be used in plexus ...?
In parent pom https://github.com/codehaus-plexus/plexus-pom/blob/master/pom.xml we have defined Apache 2.0

In plexus-resources many of source files have header with MIT license.

also discussion for it: #8 

After agree for license we should correct all files headers to be consistent.

**Comment by justinmclean** [comment]
MIT is compatible with the Apache 2.0 license so there is no issues here. You can release bundle of software license under Apache 2.0 that has MIT licensed files inside it. You might want to add a LICENSE file to make it clearer what license the repo is under.
