### ISSUE TITLE
Duplicate classes on classpath

### ISSUE THREAD

**Issue by slawekjaranowski** [codehaus-plexus/plexus-resources#2]
I use in my maven project this library in version 1.1.0

Last time I have discovered that on my plugin classpath I see duplicate some classes eg. 
`org.codehaus.plexus.DefaultPlexusContainer`

This class is in two artifacts:

 - `org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1` - required by plexus-resources
 - `org.eclipse.sisu:org.eclipse.sisu.plexus:0.3.3`- required by maven-core and maven-plugin-api

I don't see any problems during plugins works, maybe something is doing by maven-core with plugin classpath.

**Comment by slachiewicz** [comment]
Please exclude `org.codehaus.plexus:plexus-container-default` that component is no longer maintained and sisu is its replacement.

**Comment by slawekjaranowski** [comment]
As I see `plexus-resources` is used in many places:  https://mvnrepository.com/artifact/org.codehaus.plexus/plexus-resources/usages
so everybody today should exclude this ... the better way is refresh dependency of this component and release new version.

If you interested I can do it.

**Comment by slachiewicz** [comment]
Yes, let's try to see how it will look like.
Some time ago I was trying do do something similar: https://github.com/codehaus-plexus/plexus-containers/pull/16/files

**Comment by slawekjaranowski** [comment]
last PR fix it
